# This values were obtained by writing down 3 points in the curve
#   rad    |   msr
# ---------+--------
#    0     |   344
# 1.5707   |   115
# -1.5707  |   573
#          |
#
# Then, fitting a 2nd order polynomial on wolfram alpha as:
# https://www.wolframalpha.com/input/?i=fit+((344,0),(573,-1.5707),(115,1.5707))
#
# This gives a linear correlation of:
# 0.00402391*P - 2.03342
#
copter_arm:
  gain: -0.0068595
  bias: 2.35948
